version: "3.8"
services:
  rustdesk-api-server:
    container_name: rustdesk-api-server
    image: ghcr.io/empowerict/rustdesk-api-server:latest
    environment:
      - HOST=0.0.0.0
      - TZ=Australia/Melbourne
      - CSRF_TRUSTED_ORIGINS=http://yourdomain.com:21114
    volumes:
      - /bict/rustdesk-api/db:/rustdesk-api-server/db
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    network_mode: bridge
    ports:
      - "21114:21114"
    restart: unless-stopped
