name: Bug Report
description: Submit an error report. Failure to respond within 3 days after receiving a response will result in closure. Attention! Asking questions without starting is very unethical.(提交错误报告。在收到回复后3天内未做出回复将导致关闭。注意！不star却提问是很没有道德的。)
title: "[Bug]: "
labels: ["bug"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please searched for historical issues and check official documentation before opening this issue.
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
    validations:
      required: true
  - type: input
    id: OS
    attributes:
      label: Operation System
      description: Which operation system are you using?
      placeholder: ex. Windows11 23H2
    validations:
      required: true
  - type: input
    id: Python
    attributes:
      label: Python Version
      description: Which version of python are you using?
      placeholder: ex. 3.8.6 64-bit
    validations:
      required: true
  - type: input
    id: PyQt
    attributes:
      label: Run type Python/Docker
      description: Which type of package start?
      placeholder: ex. docker-compose
    validations:
      required: true
