name: Docker Image CI

on:
  push:
    branches: [ "main" ]  # Changed from master to main
  pull_request:
    branches: [ "main" ]  # Changed from master to main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:  # Added permissions needed for ghcr.io
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    
    - name: Log in to GitHub Container Registry  # Added login step
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Build and push Docker image  # Modified build step to also push
      uses: docker/build-push-action@v5  # Using official Docker build-push action
      with:
        context: .
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:latest
          ghcr.io/${{ github.repository }}:${{ github.sha }}
